USE [master]
GO

/****** Object:  Database [Project2]    Script Date: 10/4/2022 11:57:56 PM ******/
CREATE DATABASE [Project2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Project2.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Project2_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Project2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Project2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Project2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Project2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Project2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Project2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Project2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Project2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Project2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Project2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Project2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Project2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Project2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Project2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Project2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Project2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Project2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Project2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Project2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Project2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Project2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Project2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Project2] SET RECOVERY FULL 
GO

ALTER DATABASE [Project2] SET  MULTI_USER 
GO

ALTER DATABASE [Project2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Project2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Project2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Project2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Project2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Project2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Project2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Project2] SET  READ_WRITE 
GO

